#define TK_EOL                           1
#define TK_RW_IF                         2
#define TK_L_PAR                         3
#define TK_R_PAR                         4
#define TK_RW_ELSE                       5
#define TK_L_BRACE                       6
#define TK_R_BRACE                       7
#define TK_COMP_EQUAL                    8
#define TK_COMP_NEQUAL                   9
#define TK_COMP_GREATER                 10
#define TK_COMP_GREATER_EQUAL           11
#define TK_COMP_LESS                    12
#define TK_COMP_LESS_EQUAL              13
#define TK_RW_PRINT                     14
#define TK_COMMA                        15
#define TK_BIN                          16
#define TK_HEX                          17
#define TK_DEC                          18
#define TK_VARIABLE                     19
#define TK_EQUAL                        20
#define OP_ADD                          21
#define OP_SUB                          22
#define OP_MULT                         23
#define OP_DIV                          24
#define TK_NUMBER                       25
