#define TK_EOL                           1
#define TK_RW_IF                         2
#define TK_L_PAR                         3
#define TK_R_PAR                         4
#define TK_RW_ELSE                       5
#define TK_RW_WHILE                      6
#define TK_L_BRACE                       7
#define TK_R_BRACE                       8
#define TK_COMP_EQUAL                    9
#define TK_COMP_NEQUAL                  10
#define TK_COMP_GREATER                 11
#define TK_COMP_GREATER_EQUAL           12
#define TK_COMP_LESS                    13
#define TK_COMP_LESS_EQUAL              14
#define TK_RW_PRINT                     15
#define TK_COMMA                        16
#define TK_BIN                          17
#define TK_HEX                          18
#define TK_DEC                          19
#define TK_VARIABLE                     20
#define TK_EQUAL                        21
#define OP_ADD                          22
#define OP_SUB                          23
#define OP_MULT                         24
#define OP_DIV                          25
#define TK_NUMBER                       26
