#define TK_EOL                           1
#define RW_CALL                          2
#define TK_ID                            3
#define TK_L_PAR                         4
#define TK_R_PAR                         5
#define TK_COMMA                         6
#define RW_RETURN                        7
#define RW_FN_DEF                        8
#define TK_RW_IF                         9
#define TK_RW_ELSE                      10
#define TK_RW_WHILE                     11
#define TK_L_BRACE                      12
#define TK_R_BRACE                      13
#define TK_COMP_EQUAL                   14
#define TK_COMP_NEQUAL                  15
#define TK_COMP_GREATER                 16
#define TK_COMP_GREATER_EQUAL           17
#define TK_COMP_LESS                    18
#define TK_COMP_LESS_EQUAL              19
#define TK_RW_PRINT                     20
#define TK_BIN                          21
#define TK_HEX                          22
#define TK_DEC                          23
#define TK_EQUAL                        24
#define OP_ADD                          25
#define OP_SUB                          26
#define OP_MULT                         27
#define OP_DIV                          28
#define TK_NUMBER                       29
