TARGET=C1Exa
EXPR_LEXER=expression_lexer.cpp
EXPR_PARSER=expression_parser.cpp
SRC_FILES=$(EXPR_LEXER) $(EXPR_PARSER) ast.cpp
BISON_SRC_FILES=$(SRC_FILES) Bison/main.cpp
LEMON_SRC_FILES=$(SRC_FILES) Lemon/main.cpp

OBJ_FILES=$(SRC_FILES)